apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-myapp
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: container-app
          image: abdelrahman1413/nodejs-image33
          ports:
            - name: httpport
              containerPort: 3000
